CREATE TABLE ACCOUNT
(
	ID BIGINT IDENTITY(1,1) CONSTRAINT Employee_Id_PK PRIMARY KEY CLUSTERED,
	EMAILADDRESS NVARCHAR(255) CONSTRAINT Employee_EmailAddress_UNIQUE UNIQUE,
	[PASSWORD] NVARCHAR(25) NOT NULL, 
	[STATUS] TINYINT NOT NULL,
	FIRSTNAME NVARCHAR(255) NOT NULL,
	LASTNAME NVARCHAR(255) NOT NULL,
	AGE TINYINT NOT NULL,
	GENDER NVARCHAR(10) NOT NULL,
	AUTHENTICATIONTOKEN NVARCHAR(200) NOT NULL,
	AUTHENTICATIONTOKEN_ISSUEON DATETIME NOT NULL,
	AUTHENTICATIONTOKEN_EXPIRATIONINSECONDS INT NOT NULL,
	AUTHENTICATIONTOKEN_TYPE NVARCHAR(25) NOT NULL,
	[ROLE] NVARCHAR(25) NOT NULL,
	CREATEDDATETIME DATETIME NOT NULL,
	UPDATEDDATETIME DATETIME NULL	 
)