CREATE TABLE ACCOUNTADDRESS
(
ID BIGINT NOT NULL PRIMARY KEY CLUSTERED,
ADDRESSLINE1 NVARCHAR(255) NULL,
ADDRESSLINE2 NVARCHAR(255) NULL,
CITY NVARCHAR(100) NULL,
[STATE] NVARCHAR(100) NULL,
COUNTRY NVARCHAR(100) NULL,
ZIPCODE NVARCHAR(20) NULL,
PHONENUMBER NVARCHAR(20) NULL,
[TYPE] NVARCHAR(20) NULL,
CREATEDDATETIME DATETIME NOT NULL DEFAULT GETDATE(),
UPDATEDDATETIME DATETIME NULL,
CONSTRAINT ACCOUNTADDRESS_ID_ACCOUNT_ID_FOREIGNKEY FOREIGN KEY(ID) REFERENCES [ACCOUNT](ID)
)

