CREATE TABLE ACCOUNTPROFILE
(
ID BIGINT NOT NULL PRIMARY KEY CLUSTERED,
TAGLINE NVARCHAR(100) NULL,
ABOUTYOUDESCRIPTION NVARCHAR(150) NULL,
WEBSITEURL NVARCHAR(500) NULL,
FACEBOOKURL NVARCHAR(500) NULL,
TUMBLRURL NVARCHAR(500) NULL,
GOOGLEPLUSURL NVARCHAR(500) NULL,
TWITTERURL NVARCHAR(500) NULL,
PINTERESTURL NVARCHAR(500) NULL,
CREATEDDATETIME DATETIME NOT NULL DEFAULT GETDATE(),
UPDATEDDATETIME DATETIME NULL,
CONSTRAINT ACCOUNTPROFILE_ID_ACCOUNT_ID_FOREIGNKEY FOREIGN KEY (ID) REFERENCES [ACCOUNT](ID) 
)